services:
  app:
    build: .
    ports:
      - "4001:3000"
    volumes:
      - .:/home/node/app
    container_name: magico-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nestjs.rule=PathPrefix(`/api/crm`)"
      - "traefik.http.routers.nestjs.middlewares=nestjs-replacepath"
      - "traefik.http.middlewares.nestjs-replacepath.replacepathregex.regex=^/api/crm/(.*)"
      - "traefik.http.middlewares.nestjs-replacepath.replacepathregex.replacement=/api/$$1"
      - "traefik.http.services.nestjs.loadbalancer.server.port=3000"
    restart: always
    env_file:
      - .env.local
    depends_on:
      - db
      - redis
      - rabbitmq
    networks:
      - gateway-network

  db:
    env_file:
      - .env.local
    platform: linux/x86_64
    image: postgres:14
    container_name: database-magico
    restart: always
    ports:
      - 5435:5432
    volumes:
      - .postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    networks:
      - gateway-network

  # db-test:
  #   image: postgres:16-alpine
  #   container_name: database-magico-test
  #   restart: always
  #   ports:
  #     - 5436:5432
  #   volumes:
  #     - .postgres_data_test:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_USER=test
  #     - POSTGRES_PASSWORD=test
  #     - POSTGRES_DB=test_db

  redis:
    env_file:
      - .env.local
    image: redis
    container_name: app-magico-redis
    restart: always
    volumes:
      - redis-data:/data
    ports:
      - 6381:6379
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - gateway-network

  rabbitmq:
    env_file:
      - .env.local
    platform: linux/arm/v7
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq-magico
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    networks:
      - gateway-network

volumes:
  redis-data:

networks:
  gateway-network:
    external: true
